language: erlang # no C/shell language support; use least-loaded worker(s)

before_install: git submodule update --init

install: make install

env:
  - TEST_OPTS=-v
  - DEFAULT_TEST_TARGET=prove

script: make test
