language: rust

sudo: false

rust: stable

script:
  - cargo build --verbose
  - cargo test --verbose
  - make -C test SHARNESS_BUILD_DIRECTORY="$PWD/target/debug" T=cheats-extract.t

branches:
  only:
    - master
