[package]
name = "codebreaker"
version = "0.1.0"
authors = ["Mathias Lafeldt <mathias.lafeldt@gmail.com>"]
links = "codebreaker"
build = "build.rs"

[lib]
name = "codebreaker"
path = "lib.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
